config/routes.rb
Rails.application.routes.draw do
  root to: 'appointments#index'
  resources :dashboards, only: [:index, :show]
  resources :doctors
  resources :patients
  resources :appointments
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :doctor
  belongs_to :patient

  validates :doctor_id, :patient_id, presence: true
  validate :attributes_presence
  validate :appointment_on_time
  validate :exceeded_thirty_minutes
  validate :appointments_times
  validate :inconsistent_hours

  def attributes_presence
    errors.add(:base, I18n.t('errors.appointments.no_appointment_date')) if appointment_date.nil?
    errors.add(:base, I18n.t('errors.appointments.no_starts_date')) if starts_at.nil?
    errors.add(:base, I18n.t('errors.appointments.no_ends_date')) if ends_at.nil?
  end

  def appointment_on_time
    return unless new_record?

    appointment = Appointment.where(starts_at: starts_at,
                                    ends_at: ends_at,
                                    appointment_date: appointment_date)
    return if appointment.empty?

    errors.add(:base, I18n.t('errors.appointments.appointment_by_date_time',
                             starts_at: starts_at.strftime('%H:%M'),
                             ends_at: ends_at.strftime('%H:%M'),
                             appointment_date: appointment_date.strftime('%d/%m/%Y')))
  end

  def inconsistent_hours
    return if ends_at.nil? || starts_at.nil?

    errors.add(:base, I18n.t('errors.appointments.inconsistent_hours')) if ends_at < starts_at
  end

  def exceeded_thirty_minutes
    return if ends_at.nil? || starts_at.nil?

    appointment_time = (ends_at - starts_at) / 60
    errors.add(:base, I18n.t('errors.appointments.appointment_minutes')) if appointment_time > 30
  end

  def appointments_times
    return if ends_at.nil? || starts_at.nil?

    start = are_in_appointment_time?(starts_at.strftime('%H:%M'))
    final = are_in_appointment_time?(ends_at.strftime('%H:%M'))
    errors.add(:base, I18n.t('errors.appointments.not_in_appointment_times')) if !start || !final
  end

  def are_in_appointment_time?(time)
    (time >= '09:00' && time <= '12:00') || (time >= '13:00' && time <= '18:00')
  end
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  has_many :appointment, dependent: :restrict_with_error

  validates :crm, uniqueness: { scope: :crm_uf }

  validate :attributes_presence

  def attributes_presence
    errors.add(:base, I18n.t('errors.appointments.no_name')) if name.nil?
    errors.add(:base, I18n.t('errors.appointments.no_crm')) if crm.nil?
    errors.add(:base, I18n.t('errors.appointments.no_crm_uf')) if crm_uf.nil?
  end
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  validates_cpf_format_of :cpf, message: 'em formato incorreto'
  validate :cpf_as_integer
  validate :attributes_presence

  def attributes_presence
    errors.add(:base, I18n.t('errors.appointments.no_name')) if name.nil?
    errors.add(:base, I18n.t('errors.appointments.no_birth_date')) if birth_date.nil?
    errors.add(:base, I18n.t('errors.appointments.no_cpf')) if cpf.nil?
  end

  def cpf_as_integer
    return if cpf.nil?

    self.cpf = cpf.gsub(/[^\d]/, '')
    duplicated_cpf = Patient.where(cpf: cpf).exists?
    errors.add(:base, 'Cpf já está em uso') if duplicated_cpf
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :appointment, only: %i[edit destroy update]
  before_action :doctor_and_patients, only: %i[new edit create update]

  def index
    @appointments = Appointment.order(starts_at: :asc)
                               .paginate(page: params[:page], per_page: 5)
  end

  def new
    @appointment = Appointment.new
  end

  def edit
    render :edit
  end

  def create
    @appointment = Appointment.new(appointment_params)
    if @appointment.save
      flash[:notice] = 'Consulta agendada com sucesso!'
      redirect_to root_url
    else
      render :new
    end
  end

  def update
    if @appointment.update appointment_params
      flash[:notice] = 'Consulta atualizada com sucesso!'
      redirect_to root_url
    else
      render :edit
    end
  end

  def destroy
    @appointment.destroy
    flash[:notice] = 'Consulta apagada com sucesso'
    redirect_to root_url
  end

  private

  def doctor_and_patients
    @doctors = Doctor.all
    @patients = Patient.all
  end

  def appointment_params
    params.require(:appointment).permit(:appointment_date, :starts_at,
                                        :ends_at, :patient_id,
                                        :doctor_id, :appointment_description)
  end

  def appointment
    @appointment = Appointment.find(params[:id])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    all_doctors
    all_dashboards_data
  end

  def search
    doctor_id = params[:doctor][:id]
    if doctor_id.empty?
      redirect_to :dashboards
    else
      dashboard_by_doctor(doctor_id)
    end
  end

  private

  def dashboard_by_doctor(doctor_id)
    all_doctors
    @doctor = Doctor.find(doctor_id)
    @dashboards = Appointment.where('doctor_id = ?', doctor_id)
    @appointments_by_doctor = Appointment.where('doctor_id = ?', doctor_id)
                                         .count
    @patients_by_doctor = Appointment.where('doctor_id = ?', doctor_id)
                                     .distinct
                                     .count(:patient_id)
  end

  def all_doctors
    @doctors = Doctor.all
  end

  def all_dashboards_data
    @dashboards = Appointment.all
                             .paginate(page: params[:page], per_page: 10)
    @appointments_count = Appointment.all
                                     .count
    @patients_count = Appointment.distinct
                                 .count(:patient_id)
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :doctor, only: %i[edit update destroy]
  before_action :ufs, only: %i[new edit create update]

  def index
    @doctors = Doctor.all
                     .paginate(page: params[:page], per_page: 5)
  end

  def new
    @doctor = Doctor.new
  end

  def edit; end

  def create
    @doctor = Doctor.new(doctor_params)
    if @doctor.save
      redirect_to doctors_url, notice: 'Médico criado com sucesso!'
    else
      render :new
    end
  end

  def update
    if @doctor.update(doctor_params)
      redirect_to doctors_url, notice: 'Médico atualizado com sucesso!'
    else
      flash[:notice] = 'Não foi possível atualizar o médico'
      render :edit
    end
  end

  def destroy
    if @doctor.destroy
      redirect_to doctors_url, notice: 'Médico apagado com sucesso!'
    else
      flash[:error] = 'Não é possível apagar o médico pois ele possui atendimentos cadastrados'
      redirect_to doctors_url
    end
  end

  private

  def ufs
    @ufs = IbgeDataService.new.ufs
  end

  def doctor
    @doctor = Doctor.find(params[:id])
  end

  def doctor_params
    params.require(:doctor).permit(:name, :crm, :crm_uf)
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[show edit update destroy]

  def index
    @patients = Patient.all
                       .paginate(page: params[:page], per_page: 5)
  end

  def show
    @appointment_by_patient = Appointment.where('patient_id = ?',
                                                params[:id])
  end

  def new
    @patient = Patient.new
  end

  def edit; end

  def create
    @patient = Patient.new(patient_params)

    if @patient.save
      redirect_to patients_url, notice: 'Paciente criado com sucesso!'
    else
      render :new
    end
  end

  def update
    if @patient.update(patient_params)
      redirect_to patients_url, notice: 'Paciente atualizado com sucesso!'
    else
      render :edit
    end
  end

  def destroy
    if @patient.destroy
      redirect_to patients_url, notice: 'Paciente apagado com sucesso!'
    else
      redirect_to patients_url, notice: 'Ocorreu um problema ao apagar o cadastro do paciente!'
    end
  end

  private

  def set_patient
    @patient = Patient.find(params[:id])
  end

  def patient_params
    params.require(:patient).permit(:name, :birth_date, :cpf)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appointments/_appointment.html.erb
<tr>
  <td><%= appointment.appointment_date.strftime("%d/%m/%Y") %></td>
  <td><%= appointment.starts_at.strftime("%H:%M") %></td>
  <td><%= appointment.ends_at.strftime("%H:%M") %></td>
  <td><%= appointment.patient.name %></td>
  <td><%= appointment.doctor.name %></td>
  <td><%= appointment.appointment_description %></td>
  <td> <%= link_to "Alterar", edit_appointment_path(appointment), class:"btn btn-default"%> </td>
  <td><%= button_to "Remover", appointment,
          method: :delete,
          class:"btn btn-danger",
          data: {confirm: "Tem certeza que quer remover a consulta?"} %></td>
</tr>

app/views/appointments/_form.html.erb
<% @appointment.errors.full_messages.each do |msg| %>
  <div class="alert alert-danger" role="alert">
    <%= msg %>
  </div>
<% end %>

<%= form_for @appointment do |form| %>
  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= form.label 'Data do atendimento' %>
        <%= form.date_field :appointment_date, class:"form-control"%>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= form.label 'Horário inicial do atendimento' %>
        <%= form.time_field :starts_at, class:"form-control"%>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= form.label 'Horário final do atendimento' %>
        <%= form.time_field :ends_at, class:"form-control", rows:4%>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= form.label 'Médico' %>
        <%= form.collection_select :doctor_id, @doctors, :id, :name, {}, class:"form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= form.label 'Paciente' %>
        <%= form.collection_select :patient_id, @patients, :id, :name, {}, class:"form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= form.label 'Descrição do atendimento' %>
        <%= form.text_field :appointment_description, class:"form-control"%>
      </div>
    </div>
  </div>
  <%= form.submit texto_da_acao, class:"btn btn-primary"%>
<% end %>

app/views/appointments/edit.html.erb
<%= render partial: "form", locals: {texto_da_acao: 'Atualizar'} %>

app/views/appointments/index.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>
<div class="alert alert-success" role="alert">
<h3>Últimas Consultas</h3>
</div>
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <td><b>Data do atendimento</b></td>
      <td><b>Hora inicial</b></td>
      <td><b>Hora final</b></td>
      <td><b>Paciente</b></td>
      <td><b>Médico</b></td>
      <td><b>Descrição</b></td>
      <td></td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <%= render @appointments %>
  </tbody>
</table>
<%= will_paginate @appointments, renderer: BootstrapPagination::Rails, previous_label: 'Primeira', next_label: 'Última' %>

app/views/appointments/new.html.erb
<%= render partial: "form", locals: {texto_da_acao: 'Criar'} %>

app/views/dashboards/_dashboard.html.erb
<% dashboard.each do |d| %>
  <tr>
    <td><%= d.appointment_date.strftime("%d/%m/%Y") %></td>
    <td><%= d.starts_at.strftime("%H:%M") %></td>
    <td><%= d.ends_at.strftime("%H:%M") %></td>
    <td><%= d.patient.name %></td>
    <td><%= d.doctor.name %></td>
    <td><%= d.appointment_description %></td>
  </tr>
<% end %>

app/views/dashboards/index.html.erb
<%= nav_bar brand: "Filtros por médico", brand_link: dashboards_path do %>
    <%= menu_group do %>
      <%= form_tag search_dashboards_path, method: :get,
       class:"navbar-form navbar-right" do %>
        <div class="form-group">
            <%= collection_select(:doctor, :id, @doctors, :id, :name, {prompt: 'Todos os médicos'}, {class: 'form-control'})  %>
            <%= button_to "Buscar", nil, class:"btn btn-default"%>
        </div>
      <% end %>
        <%= menu_item "Total de consultas realizadas: #{@appointments_count}" %>
        <%= menu_item "Pacientes diferentes atendidos: #{@patients_count}" %>
    <% end %>
<% end %>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <td><b>Data do atendimento</b></td>
      <td><b>Hora inicial</b></td>
      <td><b>Hora final</b></td>
      <td><b>Paciente</b></td>
      <td><b>Médico</b></td>
      <td><b>Descrição</b></td>
    </tr>
  </thead>
  <tbody>
    <%= render partial: 'dashboard', object: @dashboards  %>
  </tbody>
</table>
<%= will_paginate @appointments, renderer: BootstrapPagination::Rails, previous_label: 'Primeira', next_label: 'Última' %>

app/views/dashboards/search.html.erb
<%= nav_bar brand: "Filtros por médico", brand_link: dashboards_path  do %>
    <%= menu_group do %>
      <%= form_tag search_dashboards_path, method: :get,
       class:"navbar-form navbar-right" do %>
        <div class="form-group">
            <%= collection_select(:doctor, :id, @doctors, :id, :name, {include_blank: 'Todos os médicos'}, {class: 'form-control'})  %>
            <%= button_to "Buscar", nil, class:"btn btn-default"%>
        </div>
      <% end %>
      <%= menu_item "Total de consultas realizadas: #{@appointments_by_doctor}" %>
      <%= menu_item "Pacientes diferentes atendidos: #{@patients_by_doctor}" %>
      <%= menu_item "Dados do médico: #{@doctor.name.to_s}" %>
    <% end %>
<% end %>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <td><b>Data do atendimento</b></td>
      <td><b>Hora inicial</b></td>
      <td><b>Hora final</b></td>
      <td><b>Paciente</b></td>
      <td><b>Médico</b></td>
      <td><b>Descrição</b></td>
    </tr>
  </thead>
  <tbody>
    <%= render partial: 'dashboard', object: @dashboards  %>
  </tbody>
</table>

app/views/doctors/_doctor.html.erb
<tr>
  <td><%= doctor.name %></td>
  <td><%= doctor.crm.to_s + ' - ' + doctor.crm_uf.to_s %></td>
  <td> <%= link_to "Alterar", edit_doctor_path(doctor), class:"btn btn-default"%> </td>
  <td><%= button_to "Remover", doctor,
          method: :delete,
          class:"btn btn-danger",
          data: {confirm: "Tem certeza que quer remover o médico?"} %></td>
</tr>

app/views/doctors/_form.html.erb
<% @doctor.errors.full_messages.each do |msg| %>
  <div class="alert alert-danger" role="alert">
    <%= msg %>
  </div>
<% end %>

<%= form_for @doctor do |form| %>
  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= form.label :Nome %>
        <%= form.text_field :name, class:"form-control"%>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= form.label 'CRM' %>
        <%= form.number_field :crm, class:"form-control", rows:4%>
      </div>
    </div>
  </div>
    <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= form.label 'UF do CRM' %><br>
        <select name="doctor[crm_uf]" class="form-control">
          <% @ufs.each_with_index do |uf, key| %>
            <% if key == 0 && texto_da_acao == 'Atualizar'%>
              <option value="<%= @doctor.crm_uf %>"><%= @doctor.crm_uf %></option>
            <% end %>
            <option value="<%= uf['sigla'] %>"><%= uf['sigla'] %></option>
          <% end %>
        </select>
      </div>
    </div>
  </div>

  <%= form.submit texto_da_acao, class:"btn btn-primary"%>
<% end %>

app/views/doctors/edit.html.erb
<%= render partial: "form", locals: {texto_da_acao: 'Atualizar'} %>

app/views/doctors/index.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success" role="alert">
    <%= flash[:notice] %>
  </div>
<% elsif flash[:error] %>
  <div class="alert alert-danger" role="alert">
    <%= flash[:error] %>
  </div>
<% end %>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <td><b>Nome</b></td>
      <td><b>CRM</b></td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <%= render @doctors %>
  </tbody>
</table>
<%= will_paginate @appointments, renderer: BootstrapPagination::Rails, previous_label: 'Primeira', next_label: 'Última' %>

app/views/doctors/new.html.erb
<%= render partial: "form", locals: {texto_da_acao: 'Criar'} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Consultas médicas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= nav_bar brand: "Atendimentos médicos", brand_link: root_url do %>
    <%= menu_group do %>
    <%= menu_divider %>
      <%= drop_down "Consultas" do %>
        <%= menu_item "Cadastrar consultas", new_appointment_path %>
        <%= menu_item "Listagem de consultas", appointments_path %>
      <% end %>
      <%= drop_down "Médicos" do %>
        <%= menu_item "Cadastrar médicos", new_doctor_path %>
        <%= menu_item "Listagem de médicos", doctors_path %>
      <% end %>
      <%= menu_divider %>
      <%= drop_down "Pacientes" do %>
        <%= menu_item "Cadastrar pacientes", new_patient_path %>
        <%= menu_item "Listagem de pacientes", patients_path %>
      <% end %>
      <%= menu_item "Dashboard", dashboards_path %>
    <% end %>
  <% end %>
  <div class="container">
  <%= yield %>
  </div>

</body>
<div class="container">
<footer class="page-footer font-small">
    <div class="footer-copyright text-center py-3">© 2021 Copyright:
        <a href="https://github.com/gustavomendess"> <font color="red"> Gustavo Mendes </font></a>
    </div>
</footer>
</div>
</html>

app/views/patients/_form.html.erb
<% content_for :js do %>
  <%= javascript_include_tag '/javascripts/views/patients/edit' %>
<% end %>

<% @patient.errors.full_messages.each do |msg| %>
  <div class="alert alert-danger" role="alert">
    <%= msg %>
  </div>
<% end %>


<%= form_for @patient do |form| %>
  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= form.label 'Nome' %>
        <%= form.text_field :name, class:"form-control"%>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= form.label 'Data de nascimento' %>
        <%= form.date_field :birth_date, class:"form-control", rows:4%>
      </div>
    </div>
  </div>
    <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= form.label 'CPF' %>
        <%= form.text_field :cpf, class:"form-control", maxlength: "14"%>
      </div>
    </div>
  </div>

  <%= form.submit texto_da_acao, class:"btn btn-primary"%>
<% end %>

app/views/patients/_patient.html.erb
<tr>
  <td><%= patient.name %></td>
  <td><%= patient.birth_date.strftime("%d/%m/%Y") %></td>
  <td><%= CPF.new(patient.cpf).formatted %></td>
  <td> <%= link_to "Alterar", edit_patient_path(patient), class:"btn btn-default"%> </td>
  <td><%= button_to "Remover", patient,
          method: :delete,
          class:"btn btn-danger",
          data: {confirm: "Tem certeza que quer remover o paciente?"} %></td>
</tr>

app/views/patients/edit.html.erb
<%= render partial: "form", locals: {texto_da_acao: 'Atualizar'} %>

app/views/patients/index.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <td><b>Nome</b></td>
      <td><b>Data de aniversário</b></td>
      <td><b>CPF</b></td>
      <td></td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <%= render @patients %>
  </tbody>
</table>
<%= will_paginate @appointments, renderer: BootstrapPagination::Rails, previous_label: 'Primeira', next_label: 'Última' %>

app/views/patients/new.html.erb
<%= render partial: "form", locals: {texto_da_acao: 'Criar'} %>